# Form implementation generated from reading ui file 'C:\ArandanosQT\vista\utils\plantillas\CerrarSesion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CerrarSesion_Widget(object):
    def setupUi(self, CerrarSesion_Widget):
        CerrarSesion_Widget.setObjectName("CerrarSesion_Widget")
        CerrarSesion_Widget.resize(481, 263)
        CerrarSesion_Widget.setStyleSheet("background-color: rgb(213, 209, 248);")
        self.widget = QtWidgets.QWidget(parent=CerrarSesion_Widget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 481, 261))
        self.widget.setStyleSheet("        border-radius: 20px;  /* Ajusta el valor para hacer las esquinas más o menos redondas */\n"
"")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 291, 81))
        self.label_2.setStyleSheet("background-color: rgb(213, 209, 248);\n"
"color: black;  \n"
"font-family: \"Segoe UI\";\n"
"font-size: 32px;\n"
"font-weight: 650; \n"
"qproperty-alignment: AlignCenter;\n"
"\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.CancelarCerrarSession_Btn = QtWidgets.QPushButton(parent=self.widget)
        self.CancelarCerrarSession_Btn.setGeometry(QtCore.QRect(50, 130, 152, 116))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CancelarCerrarSession_Btn.setFont(font)
        self.CancelarCerrarSession_Btn.setStyleSheet("QPushButton {\n"
"\n"
"        background-color: #C03232;\n"
"        /*border: 2px solid black;*/\n"
"        color: white;  /* Cambia el color de la fuente a blanco */\n"
"        border-radius: 25px;  /* Ajusta el valor para hacer las esquinas más o menos redondas */\n"
"        padding: 10px;  /* Ajusta el margen interno del QLabel */\n"
"        border: 4px solid white;\n"
"    }")
        self.CancelarCerrarSession_Btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/iconos/botones/cerrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CancelarCerrarSession_Btn.setIcon(icon)
        self.CancelarCerrarSession_Btn.setIconSize(QtCore.QSize(72, 72))
        self.CancelarCerrarSession_Btn.setObjectName("CancelarCerrarSession_Btn")
        self.ConfirmarCerrarSession_Btn = QtWidgets.QPushButton(parent=self.widget)
        self.ConfirmarCerrarSession_Btn.setGeometry(QtCore.QRect(280, 130, 152, 116))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmarCerrarSession_Btn.setFont(font)
        self.ConfirmarCerrarSession_Btn.setStyleSheet("QPushButton {\n"
"\n"
"         background-color: #749540;\n"
"        /*border: 2px solid black;*/\n"
"        color: white;  /* Cambia el color de la fuente a blanco */\n"
"        border-radius: 25px;  /* Ajusta el valor para hacer las esquinas más o menos redondas */\n"
"        padding: 10px;  /* Ajusta el margen interno del QLabel */\n"
"        border: 4px solid white;\n"
"    }")
        self.ConfirmarCerrarSession_Btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/iconos/botones/check-mark.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ConfirmarCerrarSession_Btn.setIcon(icon1)
        self.ConfirmarCerrarSession_Btn.setIconSize(QtCore.QSize(92, 92))
        self.ConfirmarCerrarSession_Btn.setObjectName("ConfirmarCerrarSession_Btn")

        self.retranslateUi(CerrarSesion_Widget)
        self.ConfirmarCerrarSession_Btn.clicked.connect(CerrarSesion_Widget.ConfirmarCerrarSesion) # type: ignore
        self.CancelarCerrarSession_Btn.clicked.connect(CerrarSesion_Widget.CancelarCerrarSesion) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CerrarSesion_Widget)

    def retranslateUi(self, CerrarSesion_Widget):
        _translate = QtCore.QCoreApplication.translate
        CerrarSesion_Widget.setWindowTitle(_translate("CerrarSesion_Widget", "Form"))
        self.label_2.setText(_translate("CerrarSesion_Widget", "¿Seguro que desea \n"
"cerrar sesión?"))
