# Form implementation generated from reading ui file 'C:\ArandanosQT\vista\utils\plantillas\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login_Dialog(object):
    def setupUi(self, Login_Dialog):
        Login_Dialog.setObjectName("Login_Dialog")
        Login_Dialog.resize(1366, 768)
        Login_Dialog.setStyleSheet("background-color: rgb(74, 70, 108);")
        self.label = QtWidgets.QLabel(parent=Login_Dialog)
        self.label.setGeometry(QtCore.QRect(530, 0, 841, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/iconos/fondos/login3.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.UsuarioLogin_Lbl = QtWidgets.QLabel(parent=Login_Dialog)
        self.UsuarioLogin_Lbl.setGeometry(QtCore.QRect(110, 160, 141, 31))
        self.UsuarioLogin_Lbl.setStyleSheet("background-color: rgb(74, 70, 108);\n"
"color: white;  \n"
"font-family: \"Segoe UI\";\n"
"font-size: 28px;\n"
"font-weight: 600; \n"
"qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.UsuarioLogin_Lbl.setObjectName("UsuarioLogin_Lbl")
        self.PasswordLogin_Lbl = QtWidgets.QLabel(parent=Login_Dialog)
        self.PasswordLogin_Lbl.setGeometry(QtCore.QRect(110, 310, 201, 31))
        self.PasswordLogin_Lbl.setStyleSheet("background-color: rgb(74, 70, 108);\n"
"color: white;  \n"
"font-family: \"Segoe UI\";\n"
"font-size: 28px;\n"
"font-weight: 600; \n"
"qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.PasswordLogin_Lbl.setObjectName("PasswordLogin_Lbl")
        self.UsuarioLogin_lineEdit = QtWidgets.QLineEdit(parent=Login_Dialog)
        self.UsuarioLogin_lineEdit.setGeometry(QtCore.QRect(120, 210, 271, 41))
        self.UsuarioLogin_lineEdit.setStyleSheet("background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-family: \"Segoe UI Semibold\", \"Arial\", sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 660;\n"
"    qproperty-alignment: AlignLeft;\n"
"text-transform: uppercase;  /* <- Esto fuerza mayúsculas */")
        self.UsuarioLogin_lineEdit.setObjectName("UsuarioLogin_lineEdit")
        self.PasswordLogin_lineEdit = QtWidgets.QLineEdit(parent=Login_Dialog)
        self.PasswordLogin_lineEdit.setGeometry(QtCore.QRect(120, 370, 271, 41))
        self.PasswordLogin_lineEdit.setStyleSheet("background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-family: \"Segoe UI Semibold\", \"Arial\", sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 660;\n"
"    qproperty-alignment: AlignLeft;\n"
"text-transform: uppercase;  /* <- Esto fuerza mayúsculas */")
        self.PasswordLogin_lineEdit.setObjectName("PasswordLogin_lineEdit")
        self.EntrarLogin_Btn = QtWidgets.QPushButton(parent=Login_Dialog)
        self.EntrarLogin_Btn.setGeometry(QtCore.QRect(140, 450, 221, 51))
        self.EntrarLogin_Btn.setStyleSheet("QPushButton {\n"
"        background-color: rgb(74, 70, 108);\n"
"        color: white; \n"
"        border-radius: 25px; \n"
"        padding: 10px;\n"
"        border: 4px solid white;\n"
"        font-family: \"Segoe UI\";\n"
"        font-size: 22px;\n"
"        font-weight: 650; \n"
"         /*qproperty-alignment: AlignCenter;*/\n"
"    }\n"
"\n"
"\n"
"")
        self.EntrarLogin_Btn.setObjectName("EntrarLogin_Btn")

        self.retranslateUi(Login_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Login_Dialog)

    def retranslateUi(self, Login_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Login_Dialog.setWindowTitle(_translate("Login_Dialog", "Dialog"))
        self.UsuarioLogin_Lbl.setText(_translate("Login_Dialog", "USUARIO"))
        self.PasswordLogin_Lbl.setText(_translate("Login_Dialog", "CONTRASEÑA"))
        self.EntrarLogin_Btn.setText(_translate("Login_Dialog", "Entrar"))
